---
spring:
    config.activate.on-profile: default
    sql.init.platform: h2
cds:
    security:
        authentication:
            authenticateMetadataEndpoints: false
logging:
    level:
        com.sap.cds: DEBUG
        org.springframework.security: DEBUG
